name: EssentialsB_1.0
version: '${project.version}'
main: de.bencodes.Essentials
api-version: '1.20'

commands:
  commandspy:
    description: Spioniere die Commands anderer Leute
    alias: [cspy, cmdspy]
  clearchat:
    description: Leere den Chat
    alias: [chatclear]
  gm:
    description: Ändere deinen Spielmodus
  kopf:
    description: Hole dir jeden Kopf in Minecraft
  invsee:
    description: Sehe das inventar anderer
  pos:
    description: Speichere und lade Koordinaten
  day:
  night:
  i:
  fly:
  rename:
  heal:
  vanish:
    description: Mache dich unsichtbar
    aliases: [v, vanishmode]
  enderchest:
    description: Öffne die Enderchest eines anderen Spielers
    aliases: [ec, enderc, echest]